language: ruby
notifications:
  email: false
  slack:
    secure: D/HmCRi5MH7miTew1ybp75pHtF9YOfA3wLfedzcEyXMihVZXCRVHkvR2uOmcR8rL2NgExV+foWoxueIzxWNBgr8ljWi+AiB8OD7ZGQfqn4L5c9JUPAvNgmoZu05M0o7tRGXGnqN+38MydiPxbUPe5LWvo493XkJWYm9smaifrdQ=
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails test
- bundle exec rake brakeman:check
