entry:
  src: 1440
  srcset:
    - 640
    - 960
    - 1136
    - 750
    - 1334
    - 1242
    - 2208
    - 1024
    - 768
    - 2048
    - 1152
    - 1536
    - 1280
    - 1440
    - 2560
    - 2732
    - 2880
  sizes:
    - "(min-width: 1440px) 1440px"
    - 100vw
  quality: 90
  client_hints: "Width,DPR,Save-Data"
index:
  src: 640
  srcset:
    - 272
    - 327
    - 549
    - 640
    - 406
    - 810
    - 340
    - 680
  sizes:
    - "(min-width: 1440px) 340px"
    - "(min-width: 600px) calc((100vw - 64px)/3)"
    - calc((100vw - 48px)/2)
  quality: 50
  client_hints: "Width,DPR,Save-Data"
related:
  src: 348
  srcset:
    - 272
    - 327
    - 549
    - 640
    - 406
    - 812
    - 340
    - 680
  sizes:
    - "(min-width: 1440px) 340px"
    - "(min-width: 600px) calc((100vw - 64px)/3)"
    - calc((100vw - 48px)/2)
  quality: 50
  square: Yes
  client_hints: "Save-Data"
admin_entry:
  src: 560
  srcset:
    - 560
    - 670
    - 800
    - 1122
    - 1456
    - 1600
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
  quality: 60
  client_hints: "Width,DPR,Save-Data"
admin_edit:
  src: 300
  srcset:
    - 300
    - 516
    - 600
    - 626
    - 900
    - 1056
    - 1412
  sizes:
    - "(min-width: 800px) 300px"
    - calc(100vw - 60px)
  quality: 60
  client_hints: "Width,DPR,Save-Data"
map:
  src: 300
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  quality: 60
  square: Yes
  client_hints: "Save-Data"
